### ISSUE TITLE
tfhe_bg.wasm not found in Client Side Rendering - Multiple reports

### ISSUE THREAD

**Issue by kkoshiya** [FhenixProtocol/fhenix.js#29]
I think this might be similar to the other error relating to AWS, I'm not certain. This has been reported multiple times. I heard from a dev that works w Zama stack directly that Zama patched this, but again I'm not certain. 

Error: ENOENT: no such file or directory, open '/Users/user/workspace/n00b/fhe-voting/frontend/.next/server/app/tfhe_bg.wasm'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at 42046 (/Users/user/workspace/n00b/fhe-voting/frontend/.next/server/app/page.js:10:275)
    at t (/Users/user/workspace/n00b/fhe-voting/frontend/.next/server/webpack-runtime.js:1:143)
    at 8641 (/Users/user/workspace/n00b/fhe-voting/frontend/.next/server/app/page.js:2:16131)
    at n (/Users/user/workspace/n00b/fhe-voting/frontend/.next/server/app/page.js:2:481370)
    at 9920 (/Users/user/workspace/n00b/fhe-voting/frontend/.next/server/app/page.js:1:66913)
    at n (/Users/user/workspace/n00b/fhe-voting/frontend/.next/server/app/page.js:2:481370)
    at 3731 (/Users/user/workspace/n00b/fhe-voting/frontend/.next/server/app/page.js:1:64237)
    at n (/Users/user/workspace/n00b/fhe-voting/frontend/.next/server/app/page.js:2:481370)

**Comment by Cashmaney** [comment]
Any chance you could share a repro, or more details on some of these reports? I started looking at this, and a few examples would be helpful in making sure that the problem is properly solved

**Comment by kkoshiya** [comment]
I think both of these projects reported this error. https://github.com/zkoranges/fhe-voting and https://github.com/encrypted-state/dex/blob/main/contracts/SwapPair.sol

im not sure but i think it has something do with not being able to find the path the file

**Comment by kkoshiya** [comment]
this one as well: https://github.com/kkomelin/create-fhenix-dapp

running this command should cause the error: pnpm create fhenix-dapp@latest

**Comment by vmathur** [comment]
I'm having the same issue after I do npm install fhenixjs, and try to import FhenixClient into my nextjs app

**Comment by vmathur** [comment]
Linking my repo here: https://github.com/vmathur/prisoners-dilemma

**Comment by Cashmaney** [comment]
Thanks. Looking into this

**Comment by Cashmaney** [comment]
@kkoshiya @vmathur sorry for the delay, it was way more annoying than I expected. I pushed [0.3.0-alpha.0](https://www.npmjs.com/package/fhenixjs/v/0.3.0-alpha.0) for testing to see whether some things are still broken, but hopefully everything should be good now. Can you please check that next.js plays nicer now?

**Comment by vmathur** [comment]
The error looks resolved! Does this package also include the ability to encrypt bools?

**Comment by Cashmaney** [comment]
Glad to hear it!

Bool, uint8-256 & address should all be supported.

I want to run some more tests (serverless, other edge cases) before I merge this. I'll keep the issue open in the meantime so others can chime in if needed

**Comment by kkoshiya** [comment]
great just checked, seems to be working now. thanks Itzik

**Comment by alexandrecarvalheira** [comment]
0.3.0-alpha.0 Worked for me, thanks.

**Comment by Cashmaney** [comment]
I just created alpha.1 that has better support for nodejs and non browser environments (and a smaller size), but might come at the cost of having to either do a bit of config for next.js or directly use the prebundled version (which is the default for alpha.0).

Leaving this issue open while we continue to test/iterate

**Comment by alexandrecarvalheira** [comment]
i had no tfhe_bg.wasm error when running build on 0.3.0-alpha.0, but was getting:

`Error: Failed to initialize fhenixjs - is the network FHE-enabled? Error: Error initializing FhenixClient - maybe try calling with initSdk: false. LinkError: WebAssembly.instantiate(): Import #39 "wbg" "__wbindgen_add": function import requires a callable`

what i did was change version to 0.2.1 again and did a dynamic import with ssr false on the component that has the FhenixClient and it worked:

`const Token = dynamic(() => import("../components/token"), { ssr: false })`

The tfhe_bg.wasm error was being caused on server side render components, so i just had to disable that.

here is my repo: 
[https://github.com/encrypted-state/dex](https://github.com/encrypted-state/dex)

**Comment by Cashmaney** [comment]
@alexandrecarvalheira Did you try alpha.1? Issues like this should have been fixed. Also, fwiw you should always be running fhenix.js in CSR, as it is purely for user interaction, not for fetching anything static from the chain

**Comment by patty111** [comment]
I encountered the same issue, but after updating the fhenixjs version to 0.3.0-alpha i got this error message:
```
 ⨯ ./node_modules/fhenixjs/lib/esm/sdk/fhe/fhe-browser.js
Attempted import error: './tfhe_bg.wasm' does not contain a default export (imported as 'wasm').
```

**Comment by Cashmaney** [comment]
@patty111 Thanks for the report! Any chance we could get some more info - the framework you're using or even a repro ideally? We're trying to get it as simple as possible for all the different setups, but it's a challenge. In the meantime, you can also use the prebuilt umd version which should be more compatible

**Comment by orpheuslummis** [comment]
Using UMD `<script src="https://cdn.jsdelivr.net/npm/fhenixjs@0.3.0/dist/fhenix.umd.min.js"></script>` or with the latest git version 6a52957457f688e5d2421fa40d85a33d6ec8314b, or 0.3.0 via npm pkg:

This vitejs config:
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "tailwindcss";
import autoprefixer from "autoprefixer";
import wasm from "vite-plugin-wasm";
import topLevelAwait from "vite-plugin-top-level-await";

export default defineConfig({
  plugins: [wasm(), topLevelAwait(), react()],
  css: {
    postcss: {
      plugins: [tailwindcss(), autoprefixer()],
    },
  },
});
```

Leads to:
```
...
✘ [ERROR] No matching export in "vite-plugin-wasm-namespace:/Users/dev/dev/covalence-prizes/node_modules/.pnpm/fhenixjs@0.3.0/node_modules/fhenixjs/lib/esm/sdk/fhe/tfhe_bg.wasm" for import "default"

    ../node_modules/.pnpm/fhenixjs@0.3.0/node_modules/fhenixjs/lib/esm/sdk/fhe/fhe-browser.js:10:7:
      10 │ import wasm from "./tfhe_bg.wasm";
         ╵        ~~~~

/Users/dev/dev/covalence-prizes/webapp/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1472
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
../node_modules/.pnpm/fhenixjs@0.3.0/node_modules/fhenixjs/lib/esm/sdk/fhe/fhe-browser.js:10:7: ERROR: No matching export in "vite-plugin-wasm-namespace:/Users/dev/dev/covalence-prizes/node_modules/.pnpm/fhenixjs@0.3.0/node_modules/fhenixjs/lib/esm/sdk/fhe/tfhe_bg.wasm" for import "default"
    at failureErrorWithLog (/Users/dev/dev/covalence-prizes/webapp/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1472:15)
    at /Users/dev/dev/covalence-prizes/webapp/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:945:25
    at /Users/dev/dev/covalence-prizes/webapp/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v22.4.1
 ELIFECYCLE  Command failed with exit code 1.
dev@mm webapp % 
```

When adding to it:
```
  optimizeDeps: {
    exclude: ["fhenixjs"],
  },
```

We then obtain:
```
  VITE v5.4.6  ready in 363 ms
...
10:20:49 PM [vite] Pre-transform error: Failed to resolve import "wbg" from "../node_modules/.pnpm/fhenixjs@0.3.0/node_modules/fhenixjs/lib/esm/sdk/fhe/tfhe_bg-browser.wasm". Does the file exist?
10:20:50 PM [vite] Internal server error: Failed to resolve import "wbg" from "../node_modules/.pnpm/fhenixjs@0.3.0/node_modules/fhenixjs/lib/esm/sdk/fhe/tfhe_bg-browser.wasm". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/dev/dev/covalence-prizes/node_modules/.pnpm/fhenixjs@0.3.0/node_modules/fhenixjs/lib/esm/sdk/fhe/tfhe_bg-browser.wasm:6:3498
  4  |  import __vite__initWasm from "/__vite-plugin-wasm-helper"
  5  |  
  6  |  import { __wbindgen_bigint_from_u64 as __vite__wasmImport_0_0, __wbindgen_shr as __vite__wasmImport_0_1, __wbindgen_object_drop_ref as __vite__wasmImport_0_2, __wbindgen_bigint_from_i64 as __vite__wasmImport_0_3, __wbindgen_jsval_eq as __vite__wasmImport_0_4, __wbindgen_error_new as __vite__wasmImport_0_5, __wbindgen_bigint_from_i128 as __vite__wasmImport_0_6, __wbindgen_bigint_from_u128 as __vite__wasmImport_0_7, __wbg_fheuint16_new as __vite__wasmImport_0_8, __wbg_fheuint160_new as __vite__wasmImport_0_9, __wbg_fheuint256_new as __vite__wasmImport_0_10, __wbg_fheuint32_new as __vite__wasmImport_0_11, __wbg_fheuint128_new as __vite__wasmImport_0_12, __wbg_fheuint8_new as __vite__wasmImport_0_13, __wbg_fheuint64_new as __vite__wasmImport_0_14, __wbg_fheint32_new as __vite__wasmImport_0_15, __wbg_fheint64_new as __vite__wasmImport_0_16, __wbg_fhebool_new as __vite__wasmImport_0_17, __wbg_fheint256_new as __vite__wasmImport_0_18, __wbg_fheint160_new as __vite__wasmImport_0_19, __wbg_fheint16_new as __vite__wasmImport_0_20, __wbg_fheint8_new as __vite__wasmImport_0_21, __wbg_fheint128_new as __vite__wasmImport_0_22, __wbindgen_boolean_get as __vite__wasmImport_0_23, __wbindgen_bigint_from_str as __vite__wasmImport_0_24, __wbindgen_bit_and as __vite__wasmImport_0_25, __wbindgen_number_new as __vite__wasmImport_0_26, __wbindgen_lt as __vite__wasmImport_0_27, __wbindgen_neg as __vite__wasmImport_0_28, __wbindgen_shl as __vite__wasmImport_0_29, __wbindgen_add as __vite__wasmImport_0_30, __wbindgen_bit_or as __vite__wasmImport_0_31, __wbg_new_abda76e883ba8a5f as __vite__wasmImport_0_32, __wbg_stack_658279fe44541cf6 as __vite__wasmImport_0_33, __wbg_error_f851667af71bcfc6 as __vite__wasmImport_0_34, __wbg_crypto_70a96de3b6b73dac as __vite__wasmImport_0_35, __wbindgen_is_object as __vite__wasmImport_0_36, __wbg_process_dd1577445152112e as __vite__wasmImport_0_37, __wbg_versions_58036bec3add9e6f as __vite__wasmImport_0_38, __wbg_node_6a9d28205ed5b0d8 as __vite__wasmImport_0_39, __wbindgen_is_string as __vite__wasmImport_0_40, __wbg_require_f05d779769764e82 as __vite__wasmImport_0_41, __wbindgen_string_new as __vite__wasmImport_0_42, __wbg_msCrypto_adbc770ec9eca9c7 as __vite__wasmImport_0_43, __wbg_randomFillSync_e950366c42764a07 as __vite__wasmImport_0_44, __wbg_getRandomValues_3774744e221a22ad as __vite__wasmImport_0_45, __wbindgen_is_function as __vite__wasmImport_0_46, __wbg_newnoargs_e643855c6572a4a8 as __vite__wasmImport_0_47, __wbg_call_f96b398515635514 as __vite__wasmImport_0_48, __wbg_self_b9aad7f1c618bfaf as __vite__wasmImport_0_49, __wbg_window_55e469842c98b086 as __vite__wasmImport_0_50, __wbg_globalThis_d0957e302752547e as __vite__wasmImport_0_51, __wbg_global_ae2f87312b8987fb as __vite__wasmImport_0_52, __wbindgen_is_undefined as __vite__wasmImport_0_53, __wbg_call_35782e9a1aa5e091 as __vite__wasmImport_0_54, __wbg_buffer_fcbfb6d88b2732e9 as __vite__wasmImport_0_55, __wbg_newwithbyteoffsetandlength_92c251989c485785 as __vite__wasmImport_0_56, __wbg_new_bc5d9aad3f9ac80e as __vite__wasmImport_0_57, __wbg_set_4b3aa8445ac1e91c as __vite__wasmImport_0_58, __wbg_newwithlength_89eca18f2603a999 as __vite__wasmImport_0_59, __wbg_subarray_7649d027b2b141b3 as __vite__wasmImport_0_60, __wbindgen_object_clone_ref as __vite__wasmImport_0_61, __wbindgen_bigint_get_as_i64 as __vite__wasmImport_0_62, __wbindgen_debug_string as __vite__wasmImport_0_63, __wbindgen_throw as __vite__wasmImport_0_64, __wbindgen_memory as __vite__wasmImport_0_65 } from "wbg";
     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ^
  7  |  const __vite__wasmModule = await __vite__initWasm({ "wbg": { __wbindgen_bigint_from_u64: __vite__wasmImport_0_0, __wbindgen_shr: __vite__wasmImport_0_1, __wbindgen_object_drop_ref: __vite__wasmImport_0_2, __wbindgen_bigint_from_i64: __vite__wasmImport_0_3, __wbindgen_jsval_eq: __vite__wasmImport_0_4, __wbindgen_error_new: __vite__wasmImport_0_5, __wbindgen_bigint_from_i128: __vite__wasmImport_0_6, __wbindgen_bigint_from_u128: __vite__wasmImport_0_7, __wbg_fheuint16_new: __vite__wasmImport_0_8, __wbg_fheuint160_new: __vite__wasmImport_0_9, __wbg_fheuint256_new: __vite__wasmImport_0_10, __wbg_fheuint32_new: __vite__wasmImport_0_11, __wbg_fheuint128_new: __vite__wasmImport_0_12, __wbg_fheuint8_new: __vite__wasmImport_0_13, __wbg_fheuint64_new: __vite__wasmImport_0_14, __wbg_fheint32_new: __vite__wasmImport_0_15, __wbg_fheint64_new: __vite__wasmImport_0_16, __wbg_fhebool_new: __vite__wasmImport_0_17, __wbg_fheint256_new: __vite__wasmImport_0_18, __wbg_fheint160_new: __vite__wasmImport_0_19, __wbg_fheint16_new: __vite__wasmImport_0_20, __wbg_fheint8_new: __vite__wasmImport_0_21, __wbg_fheint128_new: __vite__wasmImport_0_22, __wbindgen_boolean_get: __vite__wasmImport_0_23, __wbindgen_bigint_from_str: __vite__wasmImport_0_24, __wbindgen_bit_and: __vite__wasmImport_0_25, __wbindgen_number_new: __vite__wasmImport_0_26, __wbindgen_lt: __vite__wasmImport_0_27, __wbindgen_neg: __vite__wasmImport_0_28, __wbindgen_shl: __vite__wasmImport_0_29, __wbindgen_add: __vite__wasmImport_0_30, __wbindgen_bit_or: __vite__wasmImport_0_31, __wbg_new_abda76e883ba8a5f: __vite__wasmImport_0_32, __wbg_stack_658279fe44541cf6: __vite__wasmImport_0_33, __wbg_error_f851667af71bcfc6: __vite__wasmImport_0_34, __wbg_crypto_70a96de3b6b73dac: __vite__wasmImport_0_35, __wbindgen_is_object: __vite__wasmImport_0_36, __wbg_process_dd1577445152112e: __vite__wasmImport_0_37, __wbg_versions_58036bec3add9e6f: __vite__wasmImport_0_38, __wbg_node_6a9d28205ed5b0d8: __vite__wasmImport_0_39, __wbindgen_is_string: __vite__wasmImport_0_40, __wbg_require_f05d779769764e82: __vite__wasmImport_0_41, __wbindgen_string_new: __vite__wasmImport_0_42, __wbg_msCrypto_adbc770ec9eca9c7: __vite__wasmImport_0_43, __wbg_randomFillSync_e950366c42764a07: __vite__wasmImport_0_44, __wbg_getRandomValues_3774744e221a22ad: __vite__wasmImport_0_45, __wbindgen_is_function: __vite__wasmImport_0_46, __wbg_newnoargs_e643855c6572a4a8: __vite__wasmImport_0_47, __wbg_call_f96b398515635514: __vite__wasmImport_0_48, __wbg_self_b9aad7f1c618bfaf: __vite__wasmImport_0_49, __wbg_window_55e469842c98b086: __vite__wasmImport_0_50, __wbg_globalThis_d0957e302752547e: __vite__wasmImport_0_51, __wbg_global_ae2f87312b8987fb: __vite__wasmImport_0_52, __wbindgen_is_undefined: __vite__wasmImport_0_53, __wbg_call_35782e9a1aa5e091: __vite__wasmImport_0_54, __wbg_buffer_fcbfb6d88b2732e9: __vite__wasmImport_0_55, __wbg_newwithbyteoffsetandlength_92c251989c485785: __vite__wasmImport_0_56, __wbg_new_bc5d9aad3f9ac80e: __vite__wasmImport_0_57, __wbg_set_4b3aa8445ac1e91c: __vite__wasmImport_0_58, __wbg_newwithlength_89eca18f2603a999: __vite__wasmImport_0_59, __wbg_subarray_7649d027b2b141b3: __vite__wasmImport_0_60, __wbindgen_object_clone_ref: __vite__wasmImport_0_61, __wbindgen_bigint_get_as_i64: __vite__wasmImport_0_62, __wbindgen_debug_string: __vite__wasmImport_0_63, __wbindgen_throw: __vite__wasmImport_0_64, __wbindgen_memory: __vite__wasmImport_0_65 } }, __vite__wasmUrl);
  8  |  export const memory = __vite__wasmModule.memory;
      at TransformPluginContext._formatError (file:///Users/dev/dev/covalence-prizes/webapp/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5_terser@5.33.0/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:49192:41)
      at TransformPluginContext.error (file:///Users/dev/dev/covalence-prizes/webapp/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5_terser@5.33.0/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:49187:16)
      at normalizeUrl (file:///Users/dev/dev/covalence-prizes/webapp/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5_terser@5.33.0/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:63983:23)
      at async file:///Users/dev/dev/covalence-prizes/webapp/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5_terser@5.33.0/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:64115:39
      at async Promise.all (index 2)
      at async TransformPluginContext.transform (file:///Users/dev/dev/covalence-prizes/webapp/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5_terser@5.33.0/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:64042:7)
      at async PluginContainer.transform (file:///Users/dev/dev/covalence-prizes/webapp/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5_terser@5.33.0/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:49033:18)
      at async loadAndTransform (file:///Users/dev/dev/covalence-prizes/webapp/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5_terser@5.33.0/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:51866:27)
      at async viteTransformMiddleware (file:///Users/dev/dev/covalence-prizes/webapp/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5_terser@5.33.0/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:61823:24)
```

**Comment by ArsiAda** [comment]
It looks like tfhe_bg.wasm issues are mostly caused by bundlers (Next.js, Vite) and SSR trying to access a client-only WASM file.

A few practical tips for users:

- For Next.js, wrap imports with dynamic + ssr: false:
  const Token = dynamic(() => import("../components/token"), { ssr: false })

- For Vite, ensure you use a wasm plugin like vite-plugin-wasm and top-level-await

- Alternatively, the UMD build works in any client environment

Would be happy to draft a minimal docs / example PR showing proper setup across frameworks to help new users avoid this error.
